# Generated by Django 4.2.2 on 2023-11-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0002_alter_color_name'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webb.productcolor'),
        ),
    ]
